### ISSUE TITLE
您好，请问下dataset/zh_ras_M010/000006_hubert.pt 怎么提取啊

### ISSUE THREAD

**Issue by Firefang003** [chenht2010/SoundStorm#1]

**Comment by chenht2010** [comment]
使用fairseq提取。或者textlesslib，当然这个也是调用fairseq。

**Comment by Firefang003** [comment]
@chenht2010 大佬，能具体说说嘛，小白不是很懂😓

**Comment by chenht2010** [comment]
如果你一定和我的一样，你可以参考https://github.com/chenht2010/textlesslib， 用里面的get_hubert_chinese.py，但是你得先把模型下载下来，改名字什么的

**Comment by chenht2010** [comment]
get_hubert.py  里面是用英语的hubert，这个你做其他操作。你可以用这个试试看，可能训练出来就像老外说中文。如果嫌提取特征慢，可以把提取f0给关闭掉。

**Comment by Firefang003** [comment]
@chenht2010 [https://github.com/adelacvg/NS2VC/blob/master/preprocess.py]，这里提取的是3维的，看你代码里面的000006_hubert.pt是1维的哎
